[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
documentation = "https://docs.rs/relm/"
license = "MIT"
name = "relm"
readme = "README.adoc"
repository = "https://github.com/antoyo/relm"
version = "0.12.0"
[badges.appveyor]
branch = "master"
repository = "antoyo/relm"

[badges.travis-ci]
branch = "master"
repository = "antoyo/relm"

[dependencies]
glib = "^0.4.0"
glib-itc = "^0.4.0"
glib-sys = "^0.5.0"
gobject-sys = "^0.5.0"
gtk = "^0.3.0"
gtk-sys = "^0.5.0"
libc = "^0.2.22"

[dependencies.relm-core]
path = "relm-core"
version = "^0.12.0"

[dependencies.relm-state]
path = "relm-state"
version = "^0.12.0"

[dev-dependencies]
chrono = "^0.3.0"
gdk = "^0.7.0"
gdk-pixbuf = "^0.3.0"
json = "^0.11.13"
#may = "^0.2.0"
may = { git = "https://github.com/Xudong-Huang/may.git" }
simplelog = "^0.4.4"

[dev-dependencies.gio]
version = "^0.3.0"

[dev-dependencies.hyper]
git = "https://github.com/rust-may/hyper"

[dev-dependencies.relm-attributes]
path = "relm-attributes"
version = "^0.12.0"

[dev-dependencies.relm-derive]
path = "relm-derive"
version = "^0.12.0"

[dev-dependencies.relm-test]
path = "relm-test"
version = "^0.12.0"

[features]
nightly = []
use_impl_trait = ["relm-state/use_impl_trait"]
[[metadata.release.pre-release-replacements]]
file = "README.adoc"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""
[[metadata.release.pre-release-replacements]]
file = "src/lib.rs"
replace = "relm = \"{{version}}\""
search = "relm = \"[a-z0-9^\\.-]+\""
