[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Core streams and event loop primitives for asynchronous GUI in Rust. Foundation for the relm crate."
documentation = "https://docs.rs/relm-core/"
license = "MIT"
name = "relm-core"
repository = "https://github.com/antoyo/relm"
version = "0.12.0"
[dependencies]
crossbeam = "^0.3.2"
may = "^0.2.0"
send-cell = "^0.1.2"

[dev-dependencies]
chrono = "^0.3.0"
glib = "^0.4.0"
gtk = "^0.3.0"
